version: "3.5"

services:
  postgres:
    image: library/postgres:14.1
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", 'max_connections=10000' ]
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
      - POSTGRES_HOST_AUTH_METHOD=trust
